AWSTemplateFormatVersion: 2010-09-09
Parameters:
  TableElementName:
    Description: Table Name
    Type: String
    AllowedPattern: '[a-zA-Z0-9]*'
    MinLength: '3'
    MaxLength: '255'
    ConstraintDescription: must contain only alphanumberic characters
  HashKeyElementName:
    Description: HashType PrimaryKey Name
    Type: String
    AllowedPattern: '[a-zA-Z0-9]*'
    MinLength: '1'
    MaxLength: '2048'
    ConstraintDescription: must contain only alphanumberic characters
  HashKeyElementType:
    Description: HashType PrimaryKey Type
    Type: String
    Default: S
    AllowedPattern: '[S|N]'
    MinLength: '1'
    MaxLength: '1'
    ConstraintDescription: must be either S or N
  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: '10'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
  Paswsword:
    Description: Paswsword
    Type: String
    AllowedPattern: '[a-zA-Z0-9]*'
    MinLength: '3'
    MaxLength: '255'
    ConstraintDescription: must contain only alphanumberic characters
  PaswswordConfirm:
    Description: Confirm Paswsword
    Type: String
    AllowedPattern: '[a-zA-Z0-9]*'
    MinLength: '3'
    MaxLength: '255'
    ConstraintDescription: must contain only alphanumberic characters
Conditions:
  PaswswordConfirmation: !Not [ !Equals [!Ref Paswsword, !Ref PaswswordConfirm] ]
Resources:
  RidesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref TableElementName
      AttributeDefinitions:
        - AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
      KeySchema:
        - AttributeName: !Ref HashKeyElementName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits
Outputs:
  TableNameOutputs:
    Value: !Ref TableElementName
    Description: Table name of the newly created DynamoDB table
  PaswswordConfirmationOutputs:
    Value: "Passwords didn't match"
    Condition: PaswswordConfirmation